package model.modules;

import model.views.Employees1VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 06:13:39 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ViewObjectImpl getDepartments1() {
        return (ViewObjectImpl) findViewObject("Departments1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for Employees1_1.
     * @return Employees1_1
     */
    public Employees1VOImpl getEmployees1_1() {
        return (Employees1VOImpl) findViewObject("Employees1_1");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for Departments2.
     * @return Departments2
     */
    public ViewObjectImpl getDepartments2() {
        return (ViewObjectImpl) findViewObject("Departments2");
    }

    /**
     * Container's getter for Employees3.
     * @return Employees3
     */
    public ViewObjectImpl getEmployees3() {
        return (ViewObjectImpl) findViewObject("Employees3");
    }

    /**
     * Container's getter for Employees1_2.
     * @return Employees1_2
     */
    public Employees1VOImpl getEmployees1_2() {
        return (Employees1VOImpl) findViewObject("Employees1_2");
    }

    /**
     * Container's getter for EmpManagerFkVL1.
     * @return EmpManagerFkVL1
     */
    public ViewLinkImpl getEmpManagerFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkVL1");
    }

    /**
     * Container's getter for DeptMgrFkVL1.
     * @return DeptMgrFkVL1
     */
    public ViewLinkImpl getDeptMgrFkVL1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkVL1");
    }

    /**
     * Container's getter for EmpDeptFkVL1.
     * @return EmpDeptFkVL1
     */
    public ViewLinkImpl getEmpDeptFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkVL1");
    }

    /**
     * Container's getter for EmpManagerFkVL2.
     * @return EmpManagerFkVL2
     */
    public ViewLinkImpl getEmpManagerFkVL2() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkVL2");
    }
    
    public String findUser(String username, String password){
        Employees1VOImpl vo = getEmployees1_1();
        vo.setusername(username);
        vo.setpassword(password);
        vo.executeQuery();
        
        if(vo.hasNext()){
            System.out.println("### true ###");
            return "true";
        }
        System.out.println("### false ###");
        return "false";
    }
    
}

