package model.views.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 17 13:10:14 PDT 2019
// ---------------------------------------------------------------------
public interface DepartmentsVORow extends Row {
    void applyEmpRaise(BigDecimal amt);
}

